/**
 * Export Service — Layer 1 Core
 * Generates PDF and PPT files from slide images
 */

const PDFDocument = require('pdfkit');
const PptxGenJS = require('pptxgenjs');
const fs = require('fs');
const path = require('path');

const EXPORTS_DIR = path.join(__dirname, '..', 'tmp', 'exports');

// Ensure directory exists
if (!fs.existsSync(EXPORTS_DIR)) {
  fs.mkdirSync(EXPORTS_DIR, { recursive: true });
}

/**
 * Generate a PDF from slide images
 * Landscape A4, one slide per page, timestamp caption
 * 
 * @param {Array<{filePath: string, timestamp: string}>} slides
 * @param {string} title - Video title
 * @param {string} exportId - Unique export identifier
 * @returns {Promise<string>} Path to generated PDF
 */
async function generatePdf(slides, title, exportId) {
  const outputPath = path.join(EXPORTS_DIR, `${exportId}.pdf`);

  return new Promise((resolve, reject) => {
    try {
      const doc = new PDFDocument({
        layout: 'landscape',
        size: 'A4',
        margins: { top: 20, bottom: 40, left: 20, right: 20 },
        info: {
          Title: `${title} — Slides`,
          Author: 'VidSlides',
          Subject: 'Video slides extracted by VidSlides',
        },
      });

      const writeStream = fs.createWriteStream(outputPath);
      doc.pipe(writeStream);

      // Title page
      doc.fontSize(28)
        .fillColor('#333333')
        .text(title, 20, 200, { align: 'center', width: doc.page.width - 40 });
      
      doc.fontSize(14)
        .fillColor('#888888')
        .text(`${slides.length} slides · Generated by VidSlides`, 20, 260, { align: 'center', width: doc.page.width - 40 });

      // Slide pages
      for (let i = 0; i < slides.length; i++) {
        const slide = slides[i];
        doc.addPage();

        // Check if image file exists
        if (fs.existsSync(slide.filePath)) {
          // Calculate image dimensions to fit page
          const pageW = doc.page.width - 40; // margins
          const pageH = doc.page.height - 80; // margins + caption space

          doc.image(slide.filePath, 20, 20, {
            fit: [pageW, pageH],
            align: 'center',
            valign: 'center',
          });
        }

        // Timestamp caption at bottom
        // doc.fontSize(10)
        //   .fillColor('#999999')
        //   .text(
        //     `⏱ ${slide.timestamp}  ·  Slide ${i + 1} of ${slides.length}`,
        //     20,
        //     doc.page.height - 35,
        //     { align: 'center', width: doc.page.width - 40 }
        //   );

        // my style 
        
      }

      doc.end();

      writeStream.on('finish', () => {
        console.log(`[exportService] PDF generated: ${outputPath}`);
        resolve(outputPath);
      });

      writeStream.on('error', reject);
    } catch (err) {
      reject(new Error(`PDF generation failed: ${err.message}`));
    }
  });
}

/**
 * Generate a PowerPoint presentation from slide images
 * 16:9 widescreen, full-bleed images, timestamp in corner
 * 
 * @param {Array<{filePath: string, timestamp: string}>} slides
 * @param {string} title - Video title
 * @param {string} exportId - Unique export identifier
 * @returns {Promise<string>} Path to generated PPTX
 */
async function generatePpt(slides, title, exportId) {
  const outputPath = path.join(EXPORTS_DIR, `${exportId}.pptx`);

  try {
    const pres = new PptxGenJS();
    pres.layout = 'LAYOUT_WIDE'; // 16:9
    pres.author = 'VidSlides';
    pres.title = `${title} — Slides`;

    // Title slide
    const titleSlide = pres.addSlide();
    titleSlide.background = { color: '0a0a0f' };
    titleSlide.addText(title, {
      x: 0.5,
      y: 2.0,
      w: '90%',
      fontSize: 32,
      color: 'f1f5f9',
      fontFace: 'Arial',
      align: 'center',
    });
    titleSlide.addText(`${slides.length} slides · Generated by VidSlides`, {
      x: 0.5,
      y: 3.2,
      w: '90%',
      fontSize: 14,
      color: '94a3b8',
      fontFace: 'Arial',
      align: 'center',
    });

    // Content slides
    for (let i = 0; i < slides.length; i++) {
      const slide = slides[i];
      const contentSlide = pres.addSlide();

      // Check if image exists
      if (fs.existsSync(slide.filePath)) {
        // Read image as base64 for PptxGenJS
        const imgData = fs.readFileSync(slide.filePath);
        const base64 = imgData.toString('base64');
        const ext = path.extname(slide.filePath).toLowerCase().replace('.', '');

        contentSlide.addImage({
          data: `image/${ext === 'jpg' ? 'jpeg' : ext};base64,${base64}`,
          x: 0,
          y: 0,
          w: '100%',
          h: '100%',
          sizing: { type: 'contain', w: 13.33, h: 7.5 },
        });
      }

      // Timestamp badge in bottom-right corner
      contentSlide.addText(`⏱ ${slide.timestamp}`, {
        x: 10.5,
        y: 6.8,
        w: 2.5,
        h: 0.4,
        fontSize: 10,
        color: 'ffffff',
        fontFace: 'Arial',
        fill: { color: '000000', transparency: 50 },
        align: 'center',
        rectRadius: 0.1,
      });

      // Slide number
      contentSlide.addText(`${i + 1} / ${slides.length}`, {
        x: 0.3,
        y: 6.8,
        w: 1.5,
        h: 0.4,
        fontSize: 9,
        color: '888888',
        fontFace: 'Arial',
      });
    }

    await pres.writeFile({ fileName: outputPath });
    console.log(`[exportService] PPT generated: ${outputPath}`);
    return outputPath;

  } catch (err) {
    throw new Error(`PPT generation failed: ${err.message}`);
  }
}

module.exports = { generatePdf, generatePpt };
